#BASE_DIR ?= $(realpath ../../../)

AMREX_HOME ?= home/edelafue/amrex

USE_EB =FALSE
PRECISION  = DOUBLE
PROFILE    = FALSE
#TINY_PROFILE = TRUE

#DEBUG      = TRUE
DEBUG      = FALSE

#DIM        = 2
DIM       = 3

COMP	   = gnu

#USE_PARTICLES = TRUE

USE_MPI    = FALSE
USE_OMP    = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ../Make.EMcLAW
